// <auto-generated />
using System;
using Archi.Infrastructure.Persistence.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Archi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260215170924_outboxMessage_migration")]
    partial class outboxMessage_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Archi.Domain.FactureAggregate.Facture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("factures", "public");
                });

            modelBuilder.Entity("Archi.Domain.ProduitAggregate.Produit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDisponible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disponible");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockDisponible")
                        .HasColumnType("integer")
                        .HasColumnName("stock_disponible");

                    b.HasKey("Id");

                    b.ToTable("Produits", "public");
                });

            modelBuilder.Entity("Archi.SharedKernel.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfRetry")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccuredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProccesedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "public");
                });

            modelBuilder.Entity("Archi.Domain.FactureAggregate.Facture", b =>
                {
                    b.OwnsMany("Archi.Domain.FactureAggregate.Entities.LigneFacture", "Lignes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("ligne_facture_id");

                            b1.Property<bool>("EstVerrouille")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("FactureId")
                                .HasColumnType("uuid");

                            b1.Property<string>("NomProduit")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("PrixUnitaireHT")
                                .HasColumnType("numeric");

                            b1.Property<Guid>("ProduitId")
                                .HasColumnType("uuid")
                                .HasColumnName("produit_id");

                            b1.Property<long>("Quantite")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Tva")
                                .HasColumnType("numeric");

                            b1.Property<long>("TvaPourcentage")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("FactureId");

                            b1.ToTable("lignes_factures", "public");

                            b1.WithOwner()
                                .HasForeignKey("FactureId");
                        });

                    b.OwnsOne("Archi.Domain.FactureAggregate.ValueObjects.PrixFacture", "PrixTotal", b1 =>
                        {
                            b1.Property<Guid>("FactureId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("MontantTotalAPayer")
                                .HasColumnType("numeric")
                                .HasColumnName("montant_Total_a_payer");

                            b1.Property<decimal>("MontantTotalHt")
                                .HasColumnType("numeric")
                                .HasColumnName("montant_total_ht");

                            b1.Property<decimal>("TotalTvaEur")
                                .HasColumnType("numeric")
                                .HasColumnName("total_tva_eur");

                            b1.HasKey("FactureId");

                            b1.ToTable("factures", "public");

                            b1.WithOwner()
                                .HasForeignKey("FactureId");
                        });

                    b.Navigation("Lignes");

                    b.Navigation("PrixTotal")
                        .IsRequired();
                });

            modelBuilder.Entity("Archi.Domain.ProduitAggregate.Produit", b =>
                {
                    b.OwnsOne("Archi.Domain.ProduitAggregate.ValueObjects.PrixProduit", "PrixUnitaire", b1 =>
                        {
                            b1.Property<Guid>("ProduitId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("PrixUnitaireHt")
                                .HasColumnType("numeric")
                                .HasColumnName("prix_unitaire_ht");

                            b1.Property<decimal>("PrixUnitaireTTC")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("TvaEur")
                                .HasColumnType("numeric")
                                .HasColumnName("tva_eur");

                            b1.Property<long>("TvaPourcentage")
                                .HasColumnType("bigint")
                                .HasColumnName("tva_pourcentage");

                            b1.HasKey("ProduitId");

                            b1.ToTable("Produits", "public");

                            b1.WithOwner()
                                .HasForeignKey("ProduitId");
                        });

                    b.Navigation("PrixUnitaire")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
